const jCategory = [
    {
        index: 0,
        image: "../images/ikhokha.png",
        project: "Design branded graphics and posts for our social media campaigns.",
        title: "Graphic Designer",
        rate: "2400",
        availability: "ongoing",
        companyName: "iKhokha",
        location: "JHB",
        vacancy: "01",
        duration: "1 Month",
        description: "We’re looking for a creative graduate to design branded graphics and engaging posts for our social media campaigns. You’ll be responsible for creating eye-catching visuals that align with our brand’s look and feel, helping us connect with our audience and increase engagement across platforms.",
        workplace: "Hybrid",
        experience: "Fresh Graduate"
    },
    {
        index: 1,
        image: "../images/takealot.png",
        project: "Optimize our website content for search engines to boost visibility.",
        rate: "5000",
        availability: "one-time", 
        companyName: "Takealot",
        location: "Cape Town",
        vacancy: "02",
        duration: "2 Weeks",
        description: "Seeking an SEO specialist to enhance website content and boost visibility on search engines. Experience with keyword research, on-page optimization, and analytics is a plus.",
        workplace: "Remote",
        experience: "1-2 Years"
    },
    {
        index: 2,
        image: "../images/kena.png",
        project: "Create a visually appealing and user-friendly interface for Kena's mobile app, focusing on enhancing user engagement and accessibility features.",
        title: "UI/UX Designer",
        rate: "4500",
        availability: "short-term",
        companyName: "Kena",
        location: "Pretoria",
        vacancy: "03",
        duration: "3 Weeks",
        description: "Design a highly engaging and accessible mobile app interface for Kena. Experience with mobile UI/UX design principles is required.",
        workplace: "On-site",
        experience: "Intermediate"
    },
    {
        index: 3,
        image: "../images/payfast.png",
        project: "Implement a secure payment gateway for PayFast to streamline online transactions and enhance customer trust, ensuring compliance with industry standards.",
        title: "Payment Gateway Developer",
        rate: "3000",
        availability: "one-time",
        companyName: "PayFast",
        location: "JHB",
        vacancy: "01",
        duration: "1 Month",
        description: "Looking for a developer to implement a secure payment gateway. Must be familiar with compliance and industry standards for online transactions.",
        workplace: "Hybrid",
        experience: "2-3 Years"
    },
    {
        index: 4,
        image: "../images/pnp.png",
        project: "Create an intuitive mobile app feature that showcases real-time in-store promotions and discounts to enhance customer engagement and drive foot traffic.",
        title: "Mobile App Developer",
        rate: "3500",
        availability: "short-term",
        companyName: "Pick n Pay",
        location: "Cape Town",
        vacancy: "02",
        duration: "2 Weeks",
        description: "Develop an app feature showcasing real-time store promotions. Experience with mobile development and customer engagement strategies is beneficial.",
        workplace: "On-site",
        experience: "Entry Level"
    },
    {
        index: 5,
        image: "../images/eyerus.png",
        project: "Design and set up our email campaigns to engage customers.",
        title: "Email Marketing Specialist",
        rate: "3600",
        availability: "ongoing",
        companyName: "Eyerus",
        location: "JHB",
        vacancy: "01",
        duration: "Ongoing",
        description: "Craft engaging email campaigns to boost customer interaction and retention. Familiarity with email marketing platforms and segmentation strategies required.",
        workplace: "Remote",
        experience: "1 Year"
    },
    {
        index: 6,
        image: "../images/chillers.png",
        project: "Create a polished landing page to showcase our company’s services.",
        title: "Front-End Developer",
        rate: "2400",
        availability: "one-time",
        companyName: "Chillers",
        location: "Pretoria",
        vacancy: "01",
        duration: "1 Week",
        description: "Seeking a front-end developer to design a visually appealing and responsive landing page. Knowledge of HTML, CSS, and JavaScript is essential.",
        workplace: "Hybrid",
        experience: "Junior"
    },
    {
        index: 7,
        image: "../images/siyavula.png",
        project: "Edit and enhance our product photos for online store listings.",
        title: "Photo Editor",
        rate: "6200",
        availability: "ongoing",
        companyName: "Siyavula",
        location: "JHB",
        vacancy: "01",
        duration: "Ongoing",
        description: "We need an editor to enhance product photos for our online listings. Proficiency in photo editing software required.",
        workplace: "Remote",
        experience: "2 Years"
    },
    {
        index: 8,
        image: "../images/b.care.png",
        project: "Develop a user-friendly dashboard that allows clients to track their health metrics, set wellness goals, and receive personalized recommendations based on their activity data.",
        title: "Dashboard Developer",
        rate: "5000",
        availability: "short-term",
        companyName: "B.Care",
        location: "Cape Town",
        vacancy: "02",
        duration: "3 Weeks",
        description: "Develop a health metrics dashboard for B.Care. Experience in user interface design and dashboard creation preferred.",
        workplace: "Hybrid",
        experience: "3 Years"
    },
    {
        index: 9,
        image: "../images/esp.png.png",
        project: "Work collaboratively with the design and development teams to gather user feedback and implement iterative enhancements to the ESP platform, ensuring a seamless and user-friendly experience for all users.",
        title: "Platform Enhancements Developer",
        rate: "4500",
        availability: "ongoing",
        companyName: "ESP",
        location: "JHB",
        vacancy: "01",
        duration: "Ongoing",
        description: "Collaborate with the team to gather user feedback and make improvements to the ESP platform for enhanced user experience.",
        workplace: "On-site",
        experience: "Intermediate"
    }
];
    
